[tool.black]
exclude = '''
/(
    \.git
  | _build
  | build
  | dist
  | env
  | venv
  | tmp
)/
'''
line-length = 110
target-version = ['py36']

[tool.pycln]
all = true

[tool.isort]
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
line_length = 110
multi_line_output = 3
use_parentheses = true
